// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: activity_weight.proto

package xlsp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ↓↓↓ 原来的 message 保持不变 ↓↓↓
type ActivityWeight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Weight uint32 `protobuf:"varint,2,opt,name=Weight,proto3" json:"Weight,omitempty"`
}

func (x *ActivityWeight) Reset() {
	*x = ActivityWeight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_weight_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityWeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityWeight) ProtoMessage() {}

func (x *ActivityWeight) ProtoReflect() protoreflect.Message {
	mi := &file_activity_weight_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityWeight.ProtoReflect.Descriptor instead.
func (*ActivityWeight) Descriptor() ([]byte, []int) {
	return file_activity_weight_proto_rawDescGZIP(), []int{0}
}

func (x *ActivityWeight) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ActivityWeight) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type ActivityWeightList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ActivityWeight `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ActivityWeightList) Reset() {
	*x = ActivityWeightList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activity_weight_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityWeightList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityWeightList) ProtoMessage() {}

func (x *ActivityWeightList) ProtoReflect() protoreflect.Message {
	mi := &file_activity_weight_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityWeightList.ProtoReflect.Descriptor instead.
func (*ActivityWeightList) Descriptor() ([]byte, []int) {
	return file_activity_weight_proto_rawDescGZIP(), []int{1}
}

func (x *ActivityWeightList) GetItems() []*ActivityWeight {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_activity_weight_proto protoreflect.FileDescriptor

var file_activity_weight_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x78, 0x6c, 0x73, 0x70, 0x22, 0x38, 0x0a,
	0x0e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x40, 0x0a, 0x12, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2a, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x78,
	0x6c, 0x73, 0x70, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x57, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x19, 0x5a, 0x17, 0x65, 0x78, 0x63,
	0x65, 0x6c, 0x32, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x3b,
	0x78, 0x6c, 0x73, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_activity_weight_proto_rawDescOnce sync.Once
	file_activity_weight_proto_rawDescData = file_activity_weight_proto_rawDesc
)

func file_activity_weight_proto_rawDescGZIP() []byte {
	file_activity_weight_proto_rawDescOnce.Do(func() {
		file_activity_weight_proto_rawDescData = protoimpl.X.CompressGZIP(file_activity_weight_proto_rawDescData)
	})
	return file_activity_weight_proto_rawDescData
}

var file_activity_weight_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_activity_weight_proto_goTypes = []interface{}{
	(*ActivityWeight)(nil),     // 0: xlsp.ActivityWeight
	(*ActivityWeightList)(nil), // 1: xlsp.ActivityWeightList
}
var file_activity_weight_proto_depIdxs = []int32{
	0, // 0: xlsp.ActivityWeightList.items:type_name -> xlsp.ActivityWeight
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_activity_weight_proto_init() }
func file_activity_weight_proto_init() {
	if File_activity_weight_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_activity_weight_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityWeight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_activity_weight_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityWeightList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_activity_weight_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_activity_weight_proto_goTypes,
		DependencyIndexes: file_activity_weight_proto_depIdxs,
		MessageInfos:      file_activity_weight_proto_msgTypes,
	}.Build()
	File_activity_weight_proto = out.File
	file_activity_weight_proto_rawDesc = nil
	file_activity_weight_proto_goTypes = nil
	file_activity_weight_proto_depIdxs = nil
}
