# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: activity_weight.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61\x63tivity_weight.proto\x12\x04xlsp\",\n\x0e\x41\x63tivityWeight\x12\n\n\x02Id\x18\x01 \x01(\r\x12\x0e\n\x06Weight\x18\x02 \x01(\r\"9\n\x12\x41\x63tivityWeightList\x12#\n\x05items\x18\x01 \x03(\x0b\x32\x14.xlsp.ActivityWeightb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'activity_weight_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIVITYWEIGHT._serialized_start=31
  _ACTIVITYWEIGHT._serialized_end=75
  _ACTIVITYWEIGHTLIST._serialized_start=77
  _ACTIVITYWEIGHTLIST._serialized_end=134
# @@protoc_insertion_point(module_scope)
